FROM python:3.6-slim
MAINTAINER frankmassi@gmail.com

COPY twitter_stream /twitter_stream
WORKDIR /twitter_stream

RUN pip install --requirement requirements.txt

CMD [ "python", "stream.py", "trump" ]

