version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka
    restart: always
    expose:
      - 9092
    ports:
      - 9092:9092
    environment:
      KAFKA_CREATE_TOPICS: "tweets:1:1"
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  twitter_stream:
    build:
      context: .
      dockerfile: Dockerfile.twitter
    restart: always
    environment:
      KAFKA_SERVER: kafka:9092
    volumes:
      - ./twitter_stream:/twitter_stream
    links:
      - kafka
    env_file: ./twitter.env

  master:
    build:
      context: .
      dockerfile: Dockerfile.spark
    command: bin/spark-class org.apache.spark.deploy.master.Master -h master
    hostname: master
    environment:
      MASTER: spark://master:7077
      CONF_DIR: /conf
      PUBLIC_DNS: localhost
    expose:
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7006
      - 7077
      - 6066
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8080:8080
    volumes:
      - ./docker-spark/conf/master:/conf
      - ./docker-spark/data:/tmp/data
      - ./spark:/spark
    links:
      - kafka

  worker:
    build:
      context: .
      dockerfile: Dockerfile.spark
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
    hostname: worker
    environment:
      CONF_DIR: /conf
      WORKER_CORES: 2
      WORKER_MEMORY: 1g
      WORKER_PORT: 8881
      WORKER_WEBUI_PORT: 8081
      PUBLIC_DNS: localhost
    links:
      - master
      - kafka
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 7016
      - 8881
    ports:
      - 8081
    volumes:
      - ./docker-spark/conf/worker:/conf
      - ./docker-spark/data:/tmp/data
